### ISSUE TITLE
Use an optimizer instead of working on a grid

### ISSUE THREAD

**Issue by mgelbart** [Anmol6/DNGO-BO#1]
For example http://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fmin_l_bfgs_b.html with random restarts

**Comment by mgelbart** [comment]
For best results you'll want to use a gradient-based optimizer. TensorFlow should be able to get these gradients for you. In particular, we want the gradient of the acquisition function with respect to the "candidate input space" x. NOT the derivative w.r.t. existing data points. 

Remember to maximize not minimize.

**Comment by Anmol6** [comment]
Yes, using gradient-descent  on Tensorflow
